FROM node:22-alpine AS build

WORKDIR /usr/src/front

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL

ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/front/dist /usr/share/nginx/html

EXPOSE 80