services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
    networks:
      - public_network
    volumes:
      - db-data:/usr/src/back/database
      - ./backend/uploads:/usr/src/back/uploads

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    restart: always
    networks:
      - public_network
    depends_on:
      - backend

networks:
  public_network:
    driver: bridge

volumes:
  db-data: