"""Initial migration database

Revision ID: 611e531eb27e
Revises: 
Create Date: 2026-09-14 14:53:01.210203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611e531eb27e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_falecimento', sa.Date(), nullable=True),
    sa.Column('biografia', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('parentesco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa_destino', sa.Integer(), nullable=False),
    sa.Column('id_parente_origem', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.Enum('PAI', 'MAE', 'CONJUGE'), nullable=False),
    sa.ForeignKeyConstraint(['id_parente_origem'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pessoa_destino'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pessoa'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('senha'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('parentesco')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
